### ISSUE TITLE
Logs need to include story name

### ISSUE THREAD

**Issue by stevepeak** [asyncy/demo.asyncy.com#1]
The engine should output logs so that the demo app can pick them up per run.

Add the following json to the log: `{"id": "<id>.story"}` e.g. `{"id": "abc123.story"}`
> JSON format is required (I think) for LogDNA

**Comment by Vesuvium** [comment]
LogDNA does not require JSON. It supports passing optional information to LogDNA via an extra dictionary argument

**Comment by Vesuvium** [comment]
The logger prepends the app id and the story to each line and sends them to LogDNA
